---
- name: subscription-manager module demo
  hosts: all
  become: true
  vars:
    subscription_username: "abilla@ep.com"
    subscription_password: "glory2God"
  tasks:
    - name: Install Docker
      ansible.builtin.yum:
        name:
          - subscription-manager
        state: latest
        update_cache: true 
    
    - name: register with subscription-manager
      community.general.redhat_subscription:
        state: present
        username: "{{ subscription_username }}"
        password: "{{ subscription_password }}"
        auto_attach: true
