---
- name: install docker on redhat and centos
  hosts: all
  become: yes
  tasks:
    - name: set mydistribution
      ansible.builtin.set_fact:
        mydistribution: "{{ 'rhel' if (ansible_distribution == 'Red Hat Enterprise Linux') else (ansible_distribution | lower) }}"

    - name: install subscription-manager
      ansible.builtin.yum_repository:
        name: subscription-manager
        state: present
