---
- hosts: all
  gather_facts: False
  connection: local
  tasks:
    - name: print name
      ansible.builtin.debug:
        msg: "Abraham Augustine"

    - name: Ping test
      ansible.builtin.ping:
